[package]
name = "lbb"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jql = "3.0.0"
serde_json = "1.0.68"
